name: vong_quay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.1.3
  auto_size_text: ^2.1.0
  carousel_slider: ^2.1.0
  shared_preferences: ^0.5.7+3
  flare_flutter: ^2.0.5
  skeleton_text: any
  flutter_material_color_picker: ^1.0.5
  audioplayers: ^0.16.0
  http: ^0.12.1
  path_provider: ^1.6.14

  firebase_core: 
  firebase_analytics: 
  firebase_messaging: 
  firebase_crashlytics:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
  
  fonts:
    - family: SFURhythmRegular
      fonts:
        - asset: assets/fonts/SFURhythmRegular.TTF

    - family: UTMSwissCondensed
      fonts:
        - asset: assets/fonts/UTMSwissCondensed.TTF